# 1. Kaun se PORT pe app chalega
server.port=8080

# 2. MySQL se connect kaise kare (Database config)
spring.datasource.url=jdbc:mysql://localhost:3306/crm_db
spring.datasource.username=root
spring.datasource.password=kaku24gupta

# 3. JPA/Hibernate — tables automatically banaye ya nahi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. JWT ke liye secret key (Spring Security)
jwt.secret=mySecretKey123
jwt.expiration=86400000
springdoc.swagger-ui.path=/swagger-ui.html
spring.security.user.name=admin
spring.security.user.password=admin123
